In [2]:
import torch
from torch import nn
from torch import einsum

In [3]:
X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
K = torch.tensor([[1.0, 0.0, -1.0], [1.0, 0.0, -1.0], [1.0, 0.0, -1.0]])
X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

X, K = X.reshape(1, 1, 2, 2), K.reshape(1, 1, 3, 3)

print(X)
tconv = nn.ConvTranspose2d(
    1, 1, kernel_size=3, stride=2, padding=1, bias=False)
tconv.weight.data = X
tconv(K)

tensor([[[[1., 2.],
          [3., 4.]]]])


tensor([[[[ 4.,  0.,  0., -3.],
          [ 2.,  0.,  0., -1.],
          [ 4.,  0.,  0., -3.],
          [ 2.,  0.,  0., -1.]]]], grad_fn=<ConvolutionBackward0>)

## Tensors Declaration


In [17]:
X = torch.tensor([[1.0, 2.0], [3.0, 4.0]],
                 dtype=torch.float32)

print(X.device)

cpu


In [16]:
# for one dimensional tensors - Type casting
X = torch.tensor(64)
print(float(X))

64.0


In [5]:
X = torch.empty(size=(3, 3))  # assigns random values
print(X)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
X = torch.empty(size=(3, 3)).normal_(mean=0, std=1)  # assigns random values
print(X)

tensor([[-1.0229,  0.7070,  0.7488],
        [ 3.1215,  0.7803,  0.7066],
        [-1.6958,  0.2624,  0.1396]])


In [7]:
X = torch.zeros(size=(3, 3))
print(X)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
X = torch.rand(size=(3, 3))  # Displays uniform distribution
print(X)

tensor([[0.4541, 0.1009, 0.2872],
        [0.5071, 0.7963, 0.8843],
        [0.5211, 0.7253, 0.1685]])


In [9]:
X = torch.ones(size=(3, 3))
print(X)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [10]:
X = torch.eye(3, 3)  # Identiy matrix
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
# starts with 0 and ends at 4 (5 is excluded)
X = torch.arange(start=0, end=5, step=1)
print(X)

tensor([0, 1, 2, 3, 4])


In [12]:
# starts with 0.1 and adds a number to reach 1 after 10 steps
X = torch.linspace(start=0.2, end=1, steps=10)
print(X)

tensor([0.2000, 0.2889, 0.3778, 0.4667, 0.5556, 0.6444, 0.7333, 0.8222, 0.9111,
        1.0000])


In [13]:
# starts with 0.1 and adds a number to reach 1 after 10 steps
X = torch.diag(torch.ones(3))
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
X = torch.arange(4)  # Type Casting
print(X.dtype)
print(X.bool())
print(X.short())
print(X.half())
print(X.float().dtype)

torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0., 1., 2., 3.], dtype=torch.float16)
torch.float32


ValueError: only one element tensors can be converted to Python scalars

In [126]:
import numpy as np

X = np.zeros((5, 5))
print(X.dtype)

Y = torch.from_numpy(X)  # Convert np array to torch tensor
print(Y.dtype)

X = Y.numpy()  # Convert back to np array
print(X.dtype)

float64
torch.float64
float64


## Tensors Operations

In [127]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([9, 8, 7])

# addition
z1 = torch.add(X, Y)
z1 = X + Y
print(z1)

tensor([10, 10, 10])


In [128]:
# Division
z1 = torch.true_divide(X, Y)  # Element wise division if of equal shape
print(z1)
z1 = torch.true_divide(X, 2)  # Divides all element by 2
print(z1)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.5000, 1.0000, 1.5000])


In [129]:
# inplace operation (usually denoted by _)
# Basically Doesnt create a copy in another variable as to use less number of variable
X.add_(Y)
print(X)
X += Y
print(X)

tensor([10, 10, 10])
tensor([19, 18, 17])


In [130]:
# Power
z1 = X.pow(2)  # all elements to the power of 2
z1 = X ** 2
print(z1)

tensor([361, 324, 289])


In [131]:
# comparision
print(z1 < 1157)

tensor([True, True, True])


In [132]:
# Matrix Multiplication
a = torch.rand((2, 5))
b = torch.rand((5, 3))

print(torch.mm(a, b))
print(torch.mm(a, b).shape)

print(a.mm(b))

tensor([[1.2152, 0.6485, 0.6283],
        [1.2336, 0.5148, 0.5162]])
torch.Size([2, 3])
tensor([[1.2152, 0.6485, 0.6283],
        [1.2336, 0.5148, 0.5162]])


In [133]:
# Element wise multiplication
a = torch.rand((2, 5))
b = torch.rand((2, 5))

print(a * b)

tensor([[0.0513, 0.1789, 0.3580, 0.0205, 0.0071],
        [0.0958, 0.0217, 0.2897, 0.4585, 0.0518]])


In [134]:
# dot product = ELement wise multiplication then sum (Only 1D Array)
a = torch.rand(5)
b = torch.rand(5)
print(torch.dot(a, b))

tensor(0.9823)


In [135]:
# matrix power
a = torch.rand((5, 5))
print(a.matrix_power(3))

tensor([[2.3579, 4.1605, 3.3399, 3.4240, 3.4652],
        [3.3910, 6.0421, 4.7199, 4.7983, 4.8417],
        [3.5168, 6.2590, 4.9210, 5.0267, 5.0451],
        [2.9576, 5.1224, 3.9391, 3.7588, 4.0440],
        [2.5569, 4.1776, 3.0895, 2.8500, 3.0864]])


In [136]:
# Lineaer algebra type power of matrix
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(x.matrix_exp())

tensor([[ 51.9690,  74.7366],
        [112.1049, 164.0738]])


In [137]:
# Batch Matrix multi
batch = 32
n = 10
p = 20
d = 30

a = torch.rand((batch, n, p))
b = torch.rand((batch, p, d))

batch_mult = torch.bmm(a, b)  # shape (batch, n , d)
print(batch_mult.shape)

torch.Size([32, 10, 30])


In [138]:
x = torch.tensor([[2, 3],
                  [4, 5]])
y = torch.tensor([[2, 3],
                  [4, 5]])

sum_x = torch.sum(x, dim=0)
print('sum across dim 0 :')
print(sum_x)

values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)

# Returns indices of max value from the given dimension
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)

# For this operation, matrix needs to be in float
mean_x = torch.mean(x.float(), dim=0)

z = torch.eq(x, y)  # Element wise equality check
print(z)

sum across dim 0 :
tensor([6, 8])
tensor([[True, True],
        [True, True]])


In [139]:
torch.sort(y, dim=1, descending=True)  # sort across dimensions

torch.return_types.sort(
values=tensor([[3, 2],
        [5, 4]]),
indices=tensor([[1, 0],
        [1, 0]]))

In [140]:
# any value less than 0 and greater than 4 is set to Min and Max respectively
torch.clamp(x, min=3, max=4)

tensor([[3, 3],
        [4, 4]])

In [141]:
x = torch.tensor([0, 1, 1, 1, 1, 0], dtype=torch.bool)

print(torch.all(x))  # AND gate
print(torch.any(x))  # OR gate

tensor(False)
tensor(True)


In [6]:
B = torch.randn((10, 3, 5, 3))
A = torch.randn((10, 3, 5, 2))

# let A be (b,i,j,k)
# B will be (b,i,j,m)
# if B transpose is (b,i,m,j)
# then final result will be (bimj)*(bijk) = (b,i,m,k)

final = einsum("bijm, bijk -> bimk", B, A)
print(final.shape)

torch.Size([10, 3, 3, 2])


# Indexing Tensors

In [142]:
x = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])
print(x[0:7])  # 0 -> 6

x = torch.rand((10, 20))  # imagine 10 days and for each 20 orders
print(x.shape)

print(x[0].shape)  # all orders of 1th day
# this reduces the dimension to 1D

print(x[0][10:20].shape)  # from 1st day, orders number 10 to 19
# This reduces the dimension to 1D

print(x[0:1][10:20].shape)  # from 1st day, orders number 10 to 19
# This maintains the dimensions

tensor([0, 1, 2, 3, 4, 5, 6])
torch.Size([10, 20])
torch.Size([20])
torch.Size([10])
torch.Size([0, 20])


In [144]:
x = torch.tensor([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11],
                  [12, 13, 14, 15]])

print(x[[0, 1], [3, 2]])  # element [0,3] and [1,2]
print(x[(x < 3) | (x > 10)])  # pick out elements in array < 3 and > 10
print(x[x.remainder(2) == 0])  # pritn all even number
print(torch.where(x < 5, x, x*2))  # if x>5 set value to x else return x*2
print(x.ndimension())  # tells us the highest dimension
print(x.numel())  # Count number of element in x

tensor([3, 6])
tensor([ 0,  1,  2, 11, 12, 13, 14, 15])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14])
tensor([[ 0,  1,  2,  3],
        [ 4, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30]])
2


# Tensor Shape

In [ ]:
x = torch.arrange(9)
print(x.size(0))  # to get value of any one dimension
print(x.shape)  # to get shape of teh tensor

In [151]:
x = torch.arange(9)
print(x)

# 3x3 = 9, This condition musdt match
x_3x3 = x.view(3, 3)
x_3x3 = x.reshape(3, 3)  # Best option
print(x_3x3)

x = x_3x3.t()  # Transpose
print(x)

# contiguous is required to make teh subspace in same space
print(x.contiguous().view(9))

x_3x3 = x.reshape(9)  # Best option
print(x_3x3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [165]:
# change shape manually
print(x.shape)
x = x.permute(0, 2, 1)  # at 0th dimension keep dimension at 0th index
# at 1st dimension keep dimension at 2nd index
# at 2nd dimension keep dimension at 1st index
print(x.shape)
# Transpose as a special case

torch.Size([10, 5, 2])
torch.Size([10, 2, 5])


In [186]:
# Sqeeuze and Unsqueeze - add or remove dimensions
x = torch.randn(10, 2)

print(x.unsqueeze(0).shape)  # unsqueeze along dim 0
print(x.unsqueeze(1).shape)  # along dimension 1
# add dimension along 0 and 2nd dimension
print(x.unsqueeze(0).unsqueeze(2).shape)

z = torch.randn(1, 10, 2)
print(z.squeeze(0).shape)
# we need 1 along that particular dimension for squeeze
print(z.squeeze(1).shape)
# hence, in the output nothing changed

torch.Size([1, 10, 2])
torch.Size([10, 1, 2])
torch.Size([1, 10, 1, 2])
torch.Size([10, 2])
torch.Size([1, 10, 2])


Till now we were manipulating dimension 
Now we will manipulates dimension values

In [166]:
# Concatenate - Stack 2 matrix wiht each other

x = torch.rand((2, 5))
y = torch.rand((2, 5))

print(torch.cat((x, y), dim=0).shape)

torch.Size([4, 5])


In [167]:
# Flatten
print(x.view(-1).shape)  # -1 is going to convert the array into flatten form

batch = 10
x = torch.rand((batch, 2, 5))
print(x.view(-1).shape)  # flatten the whole thing
print(x.view(batch, -1).shape)  # Keep batch dimension and rest of them flatten

torch.Size([10])
torch.Size([100])
torch.Size([10, 10])


In [ ]:
# example of how view works for Batched Images
x = torch.tensor([[2, 2, 2], [1, 1, 1]])
x = x.view(2, 3, 1, 1)

y = torch.tensor([[[[1, 2, 3],
                 [5, 6, 7],
                 [8, 9, 0]],
    [[1, 2, 3],
     [5, 6, 7],
     [8, 9, 0]],
    [[1, 2, 3],
     [5, 6, 7],
     [8, 9, 0]]],
    [[[1, 2, 3],
      [5, 6, 7],
      [8, 9, 0]],
     [[1, 2, 3],
     [5, 6, 7],
     [8, 9, 0]],
     [[1, 2, 3],
     [5, 6, 7],
     [8, 9, 0]]]])

z = x*y
z